version: '3'
services:
  front_end:
    build: ./front_end
    stdin_open: true
    depends_on:
      - api
    volumes:
      - ./front_end/src:/home/prodigious/front_end/src
  api:
    restart: always
    build: ./api
    volumes:
      - ./api:/home/prodigious/api
  reverse_proxy:
    image: nginx:1.15
    ports:
      - 8081:8081
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - front_end
